DAMS_03/Models/Appointment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMS_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.AppointmentTreatments = new HashSet<AppointmentTreatment>();
        }
    
        public int ID { get; set; }
        public string AppointmentID { get; set; }
        public int UserID { get; set; }
        public int ClinicHospitalID { get; set; }
        public int ApprovalState { get; set; }
        public System.DateTime PreferredDate { get; set; }
        public int PreferredTime { get; set; }
        public Nullable<int> DoctorDentistID { get; set; }
        public Nullable<int> RequestDoctorDentistID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> AppointmentTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTreatment> AppointmentTreatments { get; set; }
        public virtual ClinicHospital ClinicHospital { get; set; }
        public virtual DoctorDentist DoctorDentist { get; set; }
        public virtual DoctorDentist DoctorDentist1 { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}

DAMS_03/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAMS_03.Models;
using DAMS_03.Authorization;
using Microsoft.AspNet.Identity;

namespace DAMS_03.Controllers
{
    [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin, ClerkAdmin")]
    public class AppointmentsController : Controller
    {
        private DAMS_01Entities db = new DAMS_01Entities();

        // GET: Appointments
        public ActionResult Index(int? page, int? perpage, string search, string searchby, string orderBy, string order, int? indexby)
        {
            AppointmentIndexModel returnModel = new AppointmentIndexModel();

            int noOfResults = 10;
            if (perpage != null)
            {
                noOfResults = (int)perpage;
                returnModel.perpageNo = (int)perpage;
            }
            else
            {
                returnModel.perpageNo = 10;
            }
            if (page != null)
            {
                returnModel.pageNo = (int)page;
            }
            else
            {
                returnModel.pageNo = 1;
            }
            returnModel.search = search;
            returnModel.searchby = searchby;
            int indexBy = 0;
            if(indexby != null)
            {
                indexBy = (int)indexby;
            }

            //var appointments = db.Appointments.Include(a => a.ClinicHospital).Include(a => a.DoctorDentist).Include(a => a.DoctorDentist1).Include(a => a.UserAccount);

            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            List<AppointmentDetailViewModel> appointments = new List<AppointmentDetailViewModel>();

            if (search != null || searchby != null)
            {
                switch (searchby)
                {
                    case "user":
                        if (hospid == 0)
                        {
                            appointments = (from apt in db.Appointments
                                            join u in db.UserAccounts on apt.UserID equals u.ID
                                            join ch in db.ClinicHospitals on apt.ClinicHospitalID equals ch.ID
                                            where u.Name.Contains(search)
                                            orderby apt.ID descending
                                            select new AppointmentDetailViewModel()
                                            {
                                                ID = apt.ID,
                                                AppointmentID = apt.AppointmentID,
                                                UserName = u.Name,
                                                UserID = u.ID,
                                                ClinicHospitalName = ch.ClinicHospitalName,
                                                ClinicHospitalID = ch.ID,
                                                ApprovalState = apt.ApprovalState.ToString(),
                                                PreferredDate = apt.PreferredDate,
                                                PreferredTime = apt.PreferredTime,
                                                Remarks = apt.Remarks,
                                                AppointmentDate = apt.AppointmentDate,//
                                                AppointmentTime = apt.AppointmentTime//
                                            }).ToList();
                        }
                        else
                        {
                            appointments = (from apt in db.Appointments
                                            join u in db.UserAccounts on apt.UserID equals u.ID
                                            join ch in db.ClinicHospitals on apt.ClinicHospitalID equals ch.ID
                                            where u.Name.Contains(search)
                                            orderby apt.ID descending
                                            where ch.ID == hospid
                                            select new AppointmentDetailViewModel()
                                            {
                                                ID = apt.ID,
                                                AppointmentID = apt.AppointmentID,
                                                UserName = u.Name,
                                                UserID = u.ID,
                                                ClinicHospitalName = ch.ClinicHospitalName,
                                                ClinicHospitalID = ch.ID,
                                                ApprovalState = apt.ApprovalState.ToString(),
                                                PreferredDate = apt.PreferredDate,
                                                PreferredTime = apt.PreferredTime,
                                                Remarks = apt.Remarks,
                                                AppointmentDate = apt.AppointmentDate,//
                                                AppointmentTime = apt.AppointmentTime//
                                            }).ToList();
                        }

                        break;
                    case "dentist":
                        if (hospid == 0)
                        {
                            appointments = (from apt in db.Appointments
                                            join u in db.UserAccounts on apt.UserID equals u.ID
                                            join ch in db.ClinicHospitals on apt.ClinicHospitalID equals ch.ID
                                            join dd1 in db.DoctorDentists on apt.DoctorDentistID equals dd1.ID
                                            join dd2 in db.DoctorDentists on apt.RequestDoctorDentistID equals dd2.ID
                                            where dd1.Name.Contains(search) || dd2.Name.Contains(search)
                                            orderby apt.ID descending
                                            select new AppointmentDetailViewModel()
                                            {
                                                ID = apt.ID,
                                                AppointmentID = apt.AppointmentID,
                                                UserName = u.Name,
                                                UserID = u.ID,
                                                ClinicHospitalName = ch.ClinicHospitalName,
                                                ClinicHospitalID = ch.ID,
                                                ApprovalState = apt.ApprovalState.ToString(),
                                                PreferredDate = apt.PreferredDate,
                                                PreferredTime = apt.PreferredTime,
                                                Remarks = apt.Remarks,
                                                AppointmentDate = apt.AppointmentDate,//
                                                AppointmentTime = apt.AppointmentTime//
                                            }).ToList();
                        }
                        else
                        {
                            appointments = (from apt in db.Appointments
                                            join u in db.UserAccounts on apt.UserID equals u.ID
                                            join ch in db.ClinicHospitals on apt.ClinicHospitalID equals ch.ID
                                            join dd1 in db.DoctorDentists on apt.DoctorDentistID equals dd1.ID
                                            join dd2 in db.DoctorDentists on apt.RequestDoctorDentistID equals dd2.ID
                                            where dd1.Name.Contains(search) || dd2.Name.Contains(search)
                                            orderby apt.ID descending
                                            where ch.ID == hospid
                                            select new AppointmentDetailViewModel()
                                            {
                                                ID = apt.ID,
                                                AppointmentID = apt.AppointmentID,
                                                UserName = u.Name,
                                                UserID = u.ID,
                                                ClinicHospitalName = ch.ClinicHospitalName,
                                                ClinicHospitalID = ch.ID,
                                                ApprovalState = apt.ApprovalState.ToString(),
                                                PreferredDate = apt.PreferredDate,
                                                PreferredTime = apt.PreferredTime,
                                                Remarks = apt.Remarks,
                                                AppointmentDate = apt.AppointmentDate,//
                                                AppointmentTime = apt.AppointmentTime//
                                            }).ToList();
                        }
                        break;
                    case "date":
                        if (hospid == 0)
                        {
                            appointments = (from apt in db.Appointments
                                            join u in db.UserAccounts on apt.UserID equals u.ID

DAMS_03/Views/Appointments/Create.cshtml
@model DAMS_03.Models.AppointmentCreateViewModel
@using DAMS_03.HtmlHelpers

@{
    ViewBag.Title = "Create";
}

<h2>Create Appointment</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*@Html.HiddenFor(model => model.ClinicHospitalID)*@

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointmentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AppointmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownListFor(model => model.UserID, Model.selectUser, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@
                @*@Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })*@
                @BootstrapHtml.Dropdown("UserID", Model.selectUser, Model.UserID)
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovalState, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @{
                    List<SelectListItem> secListItems = new List<SelectListItem>();
                    secListItems.Add(new SelectListItem
                    {
                        Text = "Pending",
                        Value = "1",
                        Selected = true
                    });
                    secListItems.Add(new SelectListItem
                    {
                        Text = "Cancelled",
                        Value = "2"

                    });
                    secListItems.Add(new SelectListItem
                    {
                        Text = "Confirmed",
                        Value = "3"
                    });
                    secListItems.Add(new SelectListItem
                    {
                        Text = "Declined",
                        Value = "4"

                    });
                    secListItems.Add(new SelectListItem
                    {
                        Text = "Completed",
                        Value = "5"
                    });
                }

                @*@Html.DropDownListFor(model => model.ApprovalState, secListItems, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@
                @*@Html.EditorFor(model => model.ApprovalState, new { htmlAttributes = new { @class = "form-control" } })*@
                @BootstrapHtml.Dropdown("ApprovalState", secListItems, Model.ApprovalState)
                @Html.ValidationMessageFor(model => model.ApprovalState, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreferredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PreferredDate, new { htmlAttributes = new { @class = "datefield form-control", @placeholder = "Enter start date..." } })
                @Html.ValidationMessageFor(model => model.PreferredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreferredTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.PreferredTime, new { htmlAttributes = new { @class = "form-control" } })*@
                @BootstrapHtml.Dropdown("PreferredTime", Model.listOfTimeslots, Model.PreferredTime)
                @Html.ValidationMessageFor(model => model.PreferredTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownListFor(model => model.DoctorDentistID, Model.selectDoctorDentist, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@
                @*@Html.EditorFor(model => model.DoctorDentistID, new { htmlAttributes = new { @class = "form-control" } })*@
                @BootstrapHtml.Dropdown("DoctorDentistID", Model.selectDoctorDentist, Model.DoctorDentistID)
                @Html.ValidationMessageFor(model => model.DoctorDentistID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownListFor(model => model.RequestDoctorDentistID, Model.selectDoctorDentist, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@
                @*@Html.EditorFor(model => model.RequestDoctorDentistID, new { htmlAttributes = new { @class = "form-control" } })*@
                @BootstrapHtml.Dropdown("RequestDoctorDentistID", Model.selectDoctorDentist, Model.RequestDoctorDentistID)
                @Html.ValidationMessageFor(model => model.RequestDoctorDentistID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointmentDate, new { htmlAttributes = new { @class = "datefield form-control", @placeholder = "Enter start date..." } })
                @Html.ValidationMessageFor(model => model.AppointmentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AppointmentTime, new { htmlAttributes = new { @class = "form-control" } })*@
                @BootstrapHtml.Dropdown("AppointmentTime", Model.listOfTimeslots, Model.AppointmentTime)
                @Html.ValidationMessageFor(model => model.AppointmentTime, "", new { @class = "text-danger" })
            </div>
        </div>



        <hr />

        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-hover table-sieve">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.listOfTreatments[0].TreatmentName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.listOfTreatments[0].TreatmentDesc)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.listOfTreatments[0].IsFollowUp)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.listOfTreatments[0].Price)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.listOfTreatments[0].IsChecked)
                                </th>
                            </tr>
                        </thead>
                        <tbody id="treatmentTableBody">
                            @for (int i = 0; i < Model.listOfTreatments.Count; i++)
                            {
                                @Html.HiddenFor(modelItem => Model.listOfTreatments[i].ID)
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.listOfTreatments[i].TreatmentName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.listOfTreatments[i].TreatmentDesc)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.listOfTreatments[i].IsFollowUp)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.listOfTreatments[i].Price)
                                    </td>
                                    <td>
                                        @Html.EditorFor(modelItem => Model.listOfTreatments[i].IsChecked, new { htmlAttributes = new { @class = "form-control" } })
                                    </td>


                                </tr>
                            }
                        </tbody>
                    </table>
                    @Html.ValidationMessageFor(model => model.listOfTreatments, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("CreateSelection", "Appointments")'">
                    Back to List
                </button>
            </div>
        </div>
    </div>
                    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DAMS_03/Views/Appointments/CreateSelection.cshtml
@model IEnumerable<DAMS_03.Models.ClinicHospital>

@{
    ViewBag.Title = "Create";
}

<h2>Create Appointment</h2>

@*@using (Html.BeginForm())
    {*@
@*@Html.AntiForgeryToken()*@

<div class="form-horizontal">
    <hr />


    <div class="panel-title">
        <span><b>Select a Clinic/Hospital</b></span>
    </div>



    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover table-sieve">
                    <thead>
                        <tr>
                            <th>
                                @*@Html.DisplayNameFor(model => model.ClinicHospitalID)*@
                                ID
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.ClinicHospitalName)*@
                                Name
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.ClinicHospitalAddress)*@
                                Address
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.ClinicHospitalOpenHours)*@
                                Opening Hours
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.ClinicHospitalTel)*@
                                Tel
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.ClinicHospitalEmail)*@
                                Email
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="clinichospitalAccountTableBody">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicHospitalID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicHospitalName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicHospitalAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicHospitalOpenHours)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicHospitalTel)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClinicHospitalEmail)
                                </td>
                                <td>
                                    <button class="btn btn-primary" type="button"
                                            onclick="location.href='@Url.Action("Create", "Appointments", new { id = item.ID })'">
                                        Create appointment
                                    </button>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-2 col-md-10">
            @*<input type="submit" value="Create" class="btn btn-default" />*@
            <button class="btn btn-primary" type="button"
                    onclick="location.href='@Url.Action("Index", "Appointments")'">
                Back to List
            </button>
        </div>
    </div>
</div>
@*}*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DAMS_03/Views/Appointments/Delete.cshtml
@model DAMS_03.Models.Appointment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Appointment</h2>

<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
                @Html.LabelFor(model => model.AppointmentID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AppointmentID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovalState, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApprovalState, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreferredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PreferredDate, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreferredTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PreferredTime, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointmentDate, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointmentTime, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospital.ClinicHospitalID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospital.ClinicHospitalID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorDentist.DoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorDentist.DoctorDentistID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorDentist1.DoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorDentist1.DoctorDentistID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserAccount.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserAccount.ID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "Appointments", new { id = Model.ID })'">
                    Cancel
                </button>
            </div>
        </div>
    </div>
    }
</div>