DAMS_03/Models/AdminAccount.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMS_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminAccount()
        {
            this.AdminAccountClinicHospitals = new HashSet<AdminAccountClinicHospital>();
        }
    
        public int ID { get; set; }
        public string AdminID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string SecurityLevel { get; set; }
        public string AspNetID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminAccountClinicHospital> AdminAccountClinicHospitals { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}

DAMS_03/Models/AdminAccountsViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace DAMS_03.Models
{
    public class AdminAccountCreateModel
    {
        [Required]
        //[EmailAddress]
        //[Display(Name = "Email")]
        [Display(Name = "User ID")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        //[Required]
        //public int ID { get; set; }

        [Required]
        [Display(Name = "Organisation ID")]
        public string AdminID { get; set; }

        [Required]
        public string Name { get; set; }

        //public string Email { get; set; }

        [Required]
        //[Range(1, 3)]
        public string SecurityLevel { get; set; }

        //public string AspNetID { get; set; }



        [Display(Name = "Hospital/Clinic")]
        public List<System.Web.Mvc.SelectListItem> itemSelection { get; set; }

        [Required]
        [Display(Name = "Hospital/Clinic")]
        public string HospClinID { get; set; }


    }

    public class AdminAccountEditModel
    {
        [Required]
        //[EmailAddress]
        //[Display(Name = "Email")]
        [Display(Name = "User ID")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        //[Required]
        //[StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        //[DataType(DataType.Password)]
        //[Display(Name = "Password")]
        //public string Password { get; set; }

        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm password")]
        //[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        //public string ConfirmPassword { get; set; }

        [Required]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Organisation ID")]
        public string AdminID { get; set; }

        [Required]
        public string Name { get; set; }

        //public string Email { get; set; }

        //[Required]
        //[Range(1, 3)]
        public string SecurityLevel { get; set; }

        public string SecurityLevelID { get; set; }

        [Display(Name = "Hospital/Clinic")]
        public string HospClin { get; set; }

    }

    public class AdminAccountDetailModel
    {
        [Required]
        [Display(Name = "User ID")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Organisation ID")]
        public string AdminID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string SecurityLevel { get; set; }

        [Display(Name = "Hospital/Clinic")]
        public string HospClin { get; set; }
    }



    #region HelperClasses

    //public class listItemHospSelection
    //{
    //    public string ID { get; set; }

    //    public string Name { get; set; }

    //}

    #endregion


}

DAMS_03/Controllers/AdminAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAMS_03.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using DAMS_03.Authorization;
using System.Web.Security;

namespace DAMS_03.Controllers
{
    [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin, ClerkAdmin")]
    //[Authorize]
    public class AdminAccountsController : Controller
    {
        private DAMS_01Entities db = new DAMS_01Entities();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AdminAccountsController()
        {

        }

        public AdminAccountsController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        // GET: AdminAccounts
        public ActionResult Index()
        {

            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid == 0)
            {
                return View(db.AdminAccounts.ToList());
            }
            else
            {
                var getAdminAccountsByHospId = from aa in db.AdminAccounts
                                               join ach in db.AdminAccountClinicHospitals on aa.ID equals ach.AdminID
                                               join ch in db.ClinicHospitals on ach.ClinicHospitalID equals ch.ID
                                               where ch.ID == hospid
                                               select aa;

                return View(getAdminAccountsByHospId.ToList());
            }

        }

        // GET: AdminAccounts By Security level
        public ActionResult IndexBy(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid == 0)
            {
                var getAdminAccountsBySecId = from aa in db.AdminAccounts
                                              where aa.SecurityLevel == id.ToString()
                                              select aa;
                return View(getAdminAccountsBySecId.ToList());
            }
            else
            {
                var getAdminAccountsBySecId = from aa in db.AdminAccounts
                                              join ach in db.AdminAccountClinicHospitals on aa.ID equals ach.AdminID
                                              join ch in db.ClinicHospitals on ach.ClinicHospitalID equals ch.ID
                                              where aa.SecurityLevel == id.ToString() && ch.ID == hospid
                                              select aa;
                return View(getAdminAccountsBySecId.ToList());
            }

        }

        // GET: AdminAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminAccount adminAccount = db.AdminAccounts.Find(id);
            if (adminAccount == null)
            {
                return HttpNotFound();
            }


            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid != 0)
            {
                int matchHospid = (from ch in db.ClinicHospitals
                                   join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                                   join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                                   where aa.ID == id
                                   select ch.ID).SingleOrDefault();
                if (hospid != matchHospid)
                {
                    return RedirectToAction("Unauthorized", "Account");
                }

            }
            //end check for auth


            string UserName = (from AspNetUsers in db.AspNetUsers
                               where AspNetUsers.Id == adminAccount.AspNetID
                               select AspNetUsers.UserName).First().ToString();


            AdminAccountDetailModel adminAccountEdit = new AdminAccountDetailModel();

            adminAccountEdit.ID = adminAccount.ID;
            adminAccountEdit.AdminID = adminAccount.AdminID;
            adminAccountEdit.Name = adminAccount.Name;
            adminAccountEdit.Email = adminAccount.Email;
            //adminAccountEdit.SecurityLevel = adminAccount.SecurityLevel;

            switch (adminAccount.SecurityLevel)
            {
                case "1":
                    adminAccountEdit.SecurityLevel = "System Admin";
                    break;
                case "2":
                    adminAccountEdit.SecurityLevel = "Hospital/Clinic Admin";
                    break;
                case "3":
                    adminAccountEdit.SecurityLevel = "Hospital/Clinic Clerk";
                    break;
                default:
                    adminAccountEdit.SecurityLevel = "Error : not defined";
                    break;
            }

            adminAccountEdit.UserName = UserName;

            try
            {
                string clinhospname = (from ch in db.ClinicHospitals
                                       join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                                       join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                                       where aa.ID == id
                                       select ch.ClinicHospitalName).First().ToString();

                adminAccountEdit.HospClin = clinhospname;
            }
            catch (Exception)
            {
                adminAccountEdit.HospClin = " - ";
            }

            return View(adminAccountEdit);
        }


        //[HttpGet]
        // GET: AdminAccounts/Create
        [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin")]
        public ActionResult Create()
        {
            //var tuple = new Tuple<AdminAccount, RegisterViewModel>(new AdminAccount(), new RegisterViewModel());

            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();
            //end check for auth

            AdminAccountCreateModel returnmodel = new AdminAccountCreateModel();

            returnmodel.itemSelection = new List<SelectListItem>();

            if (hospid != 0)
            {
                var listOfHosp = from ClinHosp in db.ClinicHospitals
                                 where ClinHosp.ID == hospid
                                 select new SelectListItem()
                                 {
                                     Value = ClinHosp.ID.ToString(),
                                     Text = ClinHosp.ClinicHospitalName
                                 };
                returnmodel.itemSelection.Add(new SelectListItem()
                {
                    Value = "notselected",
                    Text = " - "
                });
                returnmodel.itemSelection.AddRange(listOfHosp.ToList<SelectListItem>());
            }
            else
            {
                var listOfHosp = from ClinHosp in db.ClinicHospitals
                                 select new SelectListItem()
                                 {
                                     Value = ClinHosp.ID.ToString(),
                                     Text = ClinHosp.ClinicHospitalName
                                 };
                returnmodel.itemSelection.Add(new SelectListItem()
                {
                    Value = "notselected",
                    Text = " - "
                });
                returnmodel.itemSelection.AddRange(listOfHosp.ToList<SelectListItem>());
            }

            return View(returnmodel);
        }

        // POST: AdminAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

DAMS_03/Views/AdminAccounts/Create.cshtml
@model DAMS_03.Models.AdminAccountCreateModel
@*@using MvcCheckBoxList.Model*@
@using DAMS_03.HtmlHelpers

@{
    ViewBag.Title = "Create";
}

<h2>Create Admin Account</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AdminID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<select id="SecurityLevel" class="form-control input-group-sm" name="SecurityLevel">
                        <option value="1">System Account</option>
                        <option value="2">Admin Account</option>
                        <option value="3" selected="selected">Clerk Account</option>
                    </select>*@
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    if (this.User.IsInRole("SysAdmin"))
                    {
                        listItems.Add(new SelectListItem
                        {
                            Text = "System Account",
                            Value = "1"
                        });
                    }
                    listItems.Add(new SelectListItem
                    {
                        Text = "Admin Account",
                        Value = "2"

                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Clerk Account",
                        Value = "3",
                        Selected = true
                    });
                }

                @*@Html.DropDownListFor(model => model.SecurityLevel, listItems, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@

                @BootstrapHtml.Dropdown("SecurityLevel", listItems, Model.SecurityLevel)

                @Html.ValidationMessageFor(model => model.SecurityLevel, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.HospClinID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @*<select id="HospClinID" class="form-control input-group-sm">

                        <option value="notselected" selected="selected"> - </option>

                        @foreach (SelectListItem item in Model.itemSelection)
                        {
                            <option value=@item.Value>@item.Text</option>

                        }

                    </select>*@

                @*@Html.DropDownListFor(model => model.HospClinID, Model.itemSelection, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@

                @BootstrapHtml.Dropdown("HospClinID", Model.itemSelection, Model.HospClinID)

                @*@Html.HiddenFor(model => model.itemSelection) lists doesnt work for hiddenfor*@

                @Html.ValidationMessageFor(model => model.HospClinID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "AdminAccounts")'">
                    Back to List
                </button>
            </div>
        </div>
    </div>
                    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DAMS_03/Views/AdminAccounts/Delete.cshtml
@model DAMS_03.Models.AdminAccountDetailModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Admin Account</h2>

<div>
    <h4>Are you sure you want to delete this?</h4>
        <hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.AdminID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AdminID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SecurityLevel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SecurityLevel, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.HospClin, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HospClin, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <button class="btn btn-primary" type="button"
                            onclick="location.href='@Url.Action("Index", "AdminAccounts")'">
                        Cancel
                    </button>
                </div>
            </div>
        </div>
}
    </div>

DAMS_03/Views/AdminAccounts/Details.cshtml
@model DAMS_03.Models.AdminAccountDetailModel

@{
    ViewBag.Title = "Details";
}

<h2>View Admin Account Details</h2>
<hr/>
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.AdminID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
               @Html.LabelFor(model => model.SecurityLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityLevel, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HospClin, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospClin, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-success" type="button"
                        onclick="location.href='@Url.Action("Edit", "AdminAccounts", new { id = Model.ID})'">
                    Update
                </button>
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "AdminAccounts")'">
                    Back to List
                </button>
            </div>
        </div>
    </div>

DAMS_03/Views/AdminAccounts/IndexBy.cshtml
@model IEnumerable<DAMS_03.Models.AdminAccount>

@{
    ViewBag.Title = "Index";
}

<h2>View Admin Accounts</h2>
<br/>

@*<div class="row">
    <div class="form-group col-md-8">
        <label class="control-label col-md-4" for="accountInput">Admin Accounts</label>
        <select id="accountInput" class="form-control input-group-sm">
            <option value="adminAccounts">Admin Accounts</option>
            <option value="adminAccountRequests">Admin Account Requests</option>
        </select>
    </div>
</div>*@

<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <div class="panel-title">
                List of Admin Accounts
                <button class="btn btn-default" type="button" style="float: right"
                        onclick="location.href='@Url.Action("Create", "AdminAccounts")'">
                    Create an Account
                </button>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-hover table-sieve">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.AdminID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.SecurityLevel)
                                </th>
                            </tr>
                        </thead>
                        <tbody id="adminAccountTableBody">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AdminID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SecurityLevel)
                                    </td>
                                    <td>
                                        <button class="btn btn-primary" type="button"
                                                onclick="location.href='@Url.Action("Details", "AdminAccounts", new { id = item.ID })'">
                                            Details
                                        </button>
                                        <button class="btn btn-success" type="button"
                                                onclick="location.href='@Url.Action("Edit", "AdminAccounts", new { id = item.ID })'">
                                            Update
                                        </button>
                                        <button class="btn btn-danger" type="button"
                                                onclick="location.href='@Url.Action("Delete", "AdminAccounts", new { id = item.ID })'">
                                            Delete
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div> <!-- end of div element with class="panel-body" -->
        </div><!-- end of div element with class="panel" -->
    </div> <!-- end of div element with  class="col-md-offset-2  col-md-8"-->
</div><!-- end of div element with class="row"-->

<script>
    // Populate the

</script>