DAMS_03/Models/Treatment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMS_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treatment()
        {
            this.AppointmentTreatments = new HashSet<AppointmentTreatment>();
            this.ClinicHospitalTreatments = new HashSet<ClinicHospitalTreatment>();
        }
    
        public int ID { get; set; }
        public string TreatmentID { get; set; }
        public string TreatmentName { get; set; }
        public string TreatmentDesc { get; set; }
        public bool IsFollowUp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTreatment> AppointmentTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicHospitalTreatment> ClinicHospitalTreatments { get; set; }
    }
}

DAMS_03/Controllers/ClinicHospitalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAMS_03.Models;
using DAMS_03.Authorization;
using Microsoft.AspNet.Identity;
using System.Data.SqlClient;

namespace DAMS_03.Controllers
{
    [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin, ClerkAdmin")]
    public class ClinicHospitalsController : Controller
    {
        private DAMS_01Entities db = new DAMS_01Entities();

        // GET: ClinicHospitals
        public ActionResult Index()
        {

            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid == 0)
            {
                return View(db.ClinicHospitals.ToList());
            }
            else
            {
                var getClinicHospitalsByHospId = from ch in db.ClinicHospitals
                                                 where ch.ID == hospid
                                                 select ch;

                return View(getClinicHospitalsByHospId.ToList());
            }

        }

        // GET: ClinicHospitals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClinicHospital clinicHospital = db.ClinicHospitals.Find(id);
            if (clinicHospital == null)
            {
                return HttpNotFound();
            }

            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid != 0)
            {
                if (hospid != id)
                {
                    return RedirectToAction("Unauthorized", "Account");
                }

            }
            //end check for auth

            List<OpeningHour> openingHours = new List<OpeningHour>();

            openingHours = (from oh in db.OpeningHours
                            where oh.ClinicHospitalID == clinicHospital.ID
                            select oh).ToList();

            List<ClinicHospitalTimeslot> timeslots = new List<ClinicHospitalTimeslot>();

            timeslots = (from ts in db.ClinicHospitalTimeslots
                         where ts.ClinicHospitalID == clinicHospital.ID
                         orderby ts.TimeslotIndex ascending
                         select ts).ToList();



            ClinicHospitalDetailsModel returnModel = new ClinicHospitalDetailsModel()
            {
                ID = clinicHospital.ID,
                ClinicHospitalID = clinicHospital.ClinicHospitalID,
                ClinicHospitalName = clinicHospital.ClinicHospitalName,
                ClinicHospitalAddress = clinicHospital.ClinicHospitalAddress,
                ClinicHospitalOpenHours = clinicHospital.ClinicHospitalOpenHours,
                ClinicHospitalTel = clinicHospital.ClinicHospitalTel,
                ClinicHospitalEmail = clinicHospital.ClinicHospitalEmail,
                IsStringOpenHours = clinicHospital.IsStringOpenHours,
                OpeningHours = openingHours,
                Timeslot = timeslots
            };

            return View(returnModel);
        }

        // GET: ClinicHospitals/Create
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Create()
        {
            ClinicHospitalCreateModel model = new ClinicHospitalCreateModel();



            model.OpeningHours = new List<OpeningHour>();

            for (int i = 1; i <= 3; i++)
            {
                model.OpeningHours.Add(new OpeningHour()
                {
                    OpeningHoursDay = i
                });
            }

            model.Timeslot = new List<ClinicHospitalTimeslot>();

            for (int i = 1; i <= 5; i++)
            {
                model.Timeslot.Add(new ClinicHospitalTimeslot()
                {
                    TimeslotIndex = i
                });
            }


            return View(model);
        }

        // POST: ClinicHospitals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Create(ClinicHospitalCreateModel model)
        {
            if (ModelState.IsValid)
            {
                ClinicHospital addClinicHospital = new ClinicHospital()
                {
                    ClinicHospitalID = model.ClinicHospitalID,
                    ClinicHospitalName = model.ClinicHospitalName,
                    ClinicHospitalAddress = model.ClinicHospitalAddress,
                    ClinicHospitalOpenHours = model.ClinicHospitalOpenHours,
                    ClinicHospitalTel = model.ClinicHospitalTel,
                    ClinicHospitalEmail = model.ClinicHospitalEmail,
                    IsStringOpenHours = model.IsStringOpenHours
                };

                db.ClinicHospitals.Add(addClinicHospital);

                for (int i = 0; i < 3; i++)
                {
                    OpeningHour addOpenHr = new OpeningHour()
                    {
                        OpeningHoursDay = (i + 1),
                        TimeRangeStart = model.OpeningHours[i].TimeRangeStart,
                        TimeRangeEnd = model.OpeningHours[i].TimeRangeEnd,
                        ClinicHospitalID = addClinicHospital.ID
                    };

                    db.OpeningHours.Add(addOpenHr);

                }

                for (int i = 0; i < 5; i++)
                {
                    if (model.Timeslot[i].TimeRangeSlotString != null)
                    {
                        ClinicHospitalTimeslot addNewTimeSlot = new ClinicHospitalTimeslot()
                        {
                            TimeslotIndex = model.Timeslot[i].TimeslotIndex,
                            TimeRangeSlotString = model.Timeslot[i].TimeRangeSlotString,
                            ClinicHospitalID = addClinicHospital.ID
                        };
                        db.ClinicHospitalTimeslots.Add(addNewTimeSlot);
                    }
                    else
                    {
                        ClinicHospitalTimeslot addNewTimeSlot = new ClinicHospitalTimeslot()
                        {
                            TimeslotIndex = model.Timeslot[i].TimeslotIndex,
                            TimeRangeSlotString = "",
                            ClinicHospitalID = addClinicHospital.ID
                        };
                        db.ClinicHospitalTimeslots.Add(addNewTimeSlot);
                    }
                }


                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                model.OpeningHours = new List<OpeningHour>();

                for (int i = 1; i <= 3; i++)
                {
                    model.OpeningHours.Add(new OpeningHour()
                    {
                        OpeningHoursDay = i
                    });
                }

                model.Timeslot = new List<ClinicHospitalTimeslot>();

                for (int i = 1; i <= 5; i++)
                {
                    model.Timeslot.Add(new ClinicHospitalTimeslot()
                    {
                        TimeslotIndex = i
                    });
                }
            }

            return View(model);
        }

        //get treatment by hospital
        // GET: ClinicHospitals/Treatments/5
        public ActionResult Treatments(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClinicHospital clinicHospital = db.ClinicHospitals.Find(id);
            if (clinicHospital == null)
            {
                return HttpNotFound();
            }

            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid != 0)
            {
                if (hospid != id)
                {
                    return RedirectToAction("Unauthorized", "Account");
                }

            }
            //end check for auth

            //var getTreatmentList = from cht in db.ClinicHospitalTreatments
            //                       where cht.ClinicHospitalID == id
            //                       select cht;

            var someTreatments = from t in db.Treatments
                                 join cht in db.ClinicHospitalTreatments on t.ID equals cht.TreatmentID

DAMS_03/Controllers/TreatmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAMS_03.Models;
using DAMS_03.Authorization;
using System.Data.SqlClient;

namespace DAMS_03.Controllers
{
    [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin, ClerkAdmin")]
    public class TreatmentsController : Controller
    {
        private DAMS_01Entities db = new DAMS_01Entities();

        // GET: Treatments
        public ActionResult Index()
        {
            return View(db.Treatments.ToList());
        }

        // GET: Treatments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Treatment treatment = db.Treatments.Find(id);
            if (treatment == null)
            {
                return HttpNotFound();
            }
            return View(treatment);
        }

        // GET: Treatments/Create
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Treatments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Create([Bind(Include = "ID,TreatmentID,TreatmentName,TreatmentDesc,IsFollowUp")] Treatment treatment)
        {
            if (ModelState.IsValid)
            {
                db.Treatments.Add(treatment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(treatment);
        }

        // GET: Treatments/Edit/5
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Treatment treatment = db.Treatments.Find(id);
            if (treatment == null)
            {
                return HttpNotFound();
            }
            return View(treatment);
        }

        // POST: Treatments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Edit([Bind(Include = "ID,TreatmentID,TreatmentName,TreatmentDesc,IsFollowUp")] Treatment treatment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(treatment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(treatment);
        }

        // GET: Treatments/Delete/5
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Treatment treatment = db.Treatments.Find(id);
            if (treatment == null)
            {
                return HttpNotFound();
            }
            return View(treatment);
        }

        // POST: Treatments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeAdmin(Roles = "SysAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {

            try
            {
                Treatment treatment = db.Treatments.Find(id);
                db.Treatments.Remove(treatment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                SqlException sqle = (SqlException)e.InnerException.InnerException;

                if (sqle.Number == 547)
                {
                    return RedirectToAction("Delete", "Treatments", new { id = id, error = "547" });
                }
                throw;
            }

            //Treatment treatment = db.Treatments.Find(id);
            //db.Treatments.Remove(treatment);
            //db.SaveChanges();
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DAMS_03/Views/ClinicHospitals/Create.cshtml
@model DAMS_03.Models.ClinicHospitalCreateModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Clinic/Hospital</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospitalID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospitalID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicHospitalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospitalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicHospitalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospitalAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospitalAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicHospitalAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospitalTel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospitalTel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicHospitalTel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospitalEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospitalEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicHospitalEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            <p><b>Opening Hours</b></p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsStringOpenHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsStringOpenHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsStringOpenHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicHospitalOpenHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicHospitalOpenHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicHospitalOpenHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        @for (int i = 0; i < 3; i++)
        {

            <div class="form-group">
                <p></p>
                <div>
                    @switch (i)
                    {
                        case 0:
                            <p><b>Monday to Fridays</b></p>
                            break;
                        case 1:
                            <p><b>Saturday</b></p>
                            break;
                        case 2:
                            <p><b>Sunday and Public Holidays</b></p>
                            break;

                    }
                </div>
            </div>

            @Html.HiddenFor(model => model.OpeningHours[i].OpeningHoursDay)

            <div class="form-group">
                @Html.LabelFor(model => model.OpeningHours[i].TimeRangeStart, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OpeningHours[i].TimeRangeStart, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OpeningHours[i].TimeRangeStart, "", new { @class = "text-danger" })
                </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OpeningHours[i].TimeRangeEnd, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OpeningHours[i].TimeRangeEnd, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OpeningHours[i].TimeRangeEnd, "", new { @class = "text-danger" })
                    </div>
                </div>

        }

        <hr />

        <div class="form-group">
            <p><b>Timeslots</b></p>
        </div>

        <div class="form-group">
            <p></p>
            <div>
                <p><b>Slot 1</b></p>
            </div>
        </div>

        @Html.HiddenFor(model => model.Timeslot[0].TimeslotIndex)

        <div class="form-group">
            @Html.LabelFor(model => model.Timeslot[0].TimeRangeSlotString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Timeslot[0].TimeRangeSlotString, new { htmlAttributes = new { @class = "form-control", placeholder = "e.g. AM / PM, 9am - 11am" } })
                @Html.ValidationMessageFor(model => model.Timeslot[0].TimeRangeSlotString, "", new { @class = "text-danger" })
            </div>
        </div>

        @for (int i = 2; i <= 5; i++)
        {

            <div class="form-group">
                <p></p>
                <div>
                    <p><b>Slot @i</b></p>
                </div>
            </div>

            @Html.HiddenFor(model => model.Timeslot[i-1].TimeslotIndex)

            <div class="form-group">
                @Html.LabelFor(model => model.Timeslot[i-1].TimeRangeSlotString, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Timeslot[i-1].TimeRangeSlotString, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model.Timeslot[i-1].TimeRangeSlotString, "", new { @class = "text-danger" })
                </div>
            </div>
            
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "ClinicHospitals")'">
                    Back to List
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DAMS_03/Views/ClinicHospitals/Delete.cshtml
@model DAMS_03.Models.ClinicHospital

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Clinic/Hospital</h2>
<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicHospitalID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClinicHospitalID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicHospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClinicHospitalName, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicHospitalAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClinicHospitalAddress, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicHospitalOpenHours, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClinicHospitalOpenHours, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicHospitalTel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClinicHospitalTel, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicHospitalEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClinicHospitalEmail, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <button class="btn btn-primary" type="button"
                            onclick="location.href='@Url.Action("Index", "ClinicHospitals")'">
                        Cancel
                    </button>
                </div>
            </div>
            @if (Request["error"] != null)
            {
                string errorNo = Request["error"];
                switch (errorNo)
                {
                    case ("547"):
                        <p style="color:red">Error : This entity cannot be deleted because it is being used by another entity.</p>
                        <br />
                        <p style="color:red">Delete all related entities?</p>
                        <br />

                        <input type="submit" value="Delete All" class="btn btn-danger" name="DeleteAll"/>

                        break;
                    default:

                        break;
                }//END switch
            }
        </div>
    }
</div>