DAMS_03/Models/DoctorDentist.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMS_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDentist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorDentist()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Appointments1 = new HashSet<Appointment>();
            this.DoctorDentistDateBookings = new HashSet<DoctorDentistDateBooking>();
        }
    
        public int ID { get; set; }
        public string DoctorDentistID { get; set; }
        public string Name { get; set; }
        public int MaxBookings { get; set; }
        public int ClinicHospitalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments1 { get; set; }
        public virtual ClinicHospital ClinicHospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorDentistDateBooking> DoctorDentistDateBookings { get; set; }
    }
}

DAMS_03/Models/DoctorDentistViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace DAMS_03.Models
{
    public class DoctorDentistCreateModel
    {
        //public int ID { get; set; }

        [Display(Name = "Dentist ID")]
        public string DoctorDentistID { get; set; }

        public string Name { get; set; }

        [Display(Name = "Hospital/Clinic")]
        public List<System.Web.Mvc.SelectListItem> itemSelection { get; set; }

        [Required]
        public string HospClinID { get; set; }

        [Required]
        public int MaxBookings { get; set; }
    }

    public class DoctorDentistDetailModel
    {    
        public int ID { get; set; }

        [Display(Name = "Dentist ID")]
        public string DoctorDentistID { get; set; }

        public string Name { get; set; }

        [Display(Name = "Hospital/Clinic")]
        public string HospClin { get; set; }
        
        public int MaxBookings { get; set; }

    }

    public class DoctorDentistEditModel
    {
        public int ID { get; set; }

        [Display(Name = "Dentist ID")]
        public string DoctorDentistID { get; set; }

        public string Name { get; set; }
        
        //[Required]
        [Display(Name = "Hospital/Clinic")]
        public string HospClin { get; set; }

        [Required]
        public int MaxBookings { get; set; }
    }

}

DAMS_03/Controllers/DoctorDentistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAMS_03.Models;
using DAMS_03.Authorization;
using Microsoft.AspNet.Identity;
using System.Data.SqlClient;

namespace DAMS_03.Controllers
{
    [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin, ClerkAdmin")]
    public class DoctorDentistsController : Controller
    {
        private DAMS_01Entities db = new DAMS_01Entities();

        // GET: DoctorDentists
        public ActionResult Index()
        {

            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid == 0)
            {
                List<DoctorDentistDetailModel> returnListofDoc = new List<DoctorDentistDetailModel>();

                foreach (DoctorDentist doctorDentist in db.DoctorDentists)
                {

                    string returnDocHospName = (from hc in db.ClinicHospitals
                                                join d in db.DoctorDentists on hc.ID equals d.ClinicHospitalID
                                                where d.ID == doctorDentist.ID
                                                select hc.ClinicHospitalName).First().ToString();

                    DoctorDentistDetailModel returnModel = new DoctorDentistDetailModel()
                    {
                        ID = doctorDentist.ID,
                        DoctorDentistID = doctorDentist.DoctorDentistID,
                        Name = doctorDentist.Name,
                        HospClin = returnDocHospName,
                        MaxBookings = doctorDentist.MaxBookings
                    };
                    returnListofDoc.Add(returnModel);
                }

                return View(returnListofDoc);
            }
            else
            {
                List<DoctorDentistDetailModel> returnListofDoc = new List<DoctorDentistDetailModel>();

                returnListofDoc = (from hc in db.ClinicHospitals
                                   join d in db.DoctorDentists on hc.ID equals d.ClinicHospitalID
                                   where hc.ID == hospid
                                   select new DoctorDentistDetailModel()
                                   {
                                       ID = d.ID,
                                       DoctorDentistID = d.DoctorDentistID,
                                       Name = d.Name,
                                       HospClin = hc.ClinicHospitalName,
                                       MaxBookings = d.MaxBookings
                                   }).ToList();

                return View(returnListofDoc);
            }


        }

        // GET: DoctorDentists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DoctorDentist doctorDentist = db.DoctorDentists.Find(id);
            if (doctorDentist == null)
            {
                return HttpNotFound();
            }

            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid != 0)
            {
                int matchHospid = (from ch in db.ClinicHospitals
                                   join dd in db.DoctorDentists on ch.ID equals dd.ClinicHospitalID
                                   where dd.ID == id
                                   select ch.ID).SingleOrDefault();
                if (hospid != matchHospid)
                {
                    return RedirectToAction("Unauthorized", "Account");
                }

            }
            //end check for auth

            DoctorDentist returnDoc = (from d in db.DoctorDentists
                                       where d.ID == id
                                       select d).SingleOrDefault();

            string returnDocHospName = (from hc in db.ClinicHospitals
                                        join d in db.DoctorDentists on hc.ID equals d.ClinicHospitalID
                                        where d.ID == id
                                        select hc.ClinicHospitalName).First().ToString();

            DoctorDentistDetailModel returnModel = new DoctorDentistDetailModel()
            {
                ID = returnDoc.ID,
                DoctorDentistID = returnDoc.DoctorDentistID,
                Name = returnDoc.Name,
                HospClin = returnDocHospName,
                MaxBookings = returnDoc.MaxBookings
            };

            return View(returnModel);
        }

        // GET: DoctorDentists/GetByDocDenID/1
        public JsonResult GetByDocDenID(int? id)
        {

            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();

            if (hospid != 0)
            {
                int matchHospid = (from ch in db.ClinicHospitals
                                   join dd in db.DoctorDentists on ch.ID equals dd.ClinicHospitalID
                                   where dd.ID == id
                                   select ch.ID).SingleOrDefault();
                if (hospid != matchHospid)
                {
                    Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                    return Json(new { Errormessage = "Unauthorized" });
                }

            }
            //end check for auth

            var dddbList = (from DDDB in db.DoctorDentistDateBookings
                            where DDDB.DoctorDentistID == id
                            select new
                            {
                                DateOfBookings = DDDB.DateOfBookings.ToString(),
                                Bookings = DDDB.Bookings,
                                DoctorDentistID = DDDB.DoctorDentistID
                            }).ToList();

            // Passing over the list(in Json format) from controller to mvc
            return Json(dddbList, JsonRequestBehavior.AllowGet);
        }

        // GET: DoctorDentists/Create
        [AuthorizeAdmin(Roles = "SysAdmin, HospAdmin")]
        public ActionResult Create()
        {

            DoctorDentistCreateModel returnmodel = new DoctorDentistCreateModel();

            returnmodel.itemSelection = new List<SelectListItem>();

            //check for auth
            string userAspId = User.Identity.GetUserId();

            int hospid = (from ch in db.ClinicHospitals
                          join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                          join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                          join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                          where aspu.Id == userAspId
                          select ch.ID).SingleOrDefault();
            //end check for auth

            if (User.IsInRole("HospAdmin") || hospid != 0)
            {
                //string userAspId = User.Identity.GetUserId();

                //int hospid = (from ch in db.ClinicHospitals
                //              join ach in db.AdminAccountClinicHospitals on ch.ID equals ach.ClinicHospitalID
                //              join aa in db.AdminAccounts on ach.AdminID equals aa.ID
                //              join aspu in db.AspNetUsers on aa.AspNetID equals aspu.Id
                //              where aspu.Id == userAspId
                //              select ch.ID).SingleOrDefault();

                var listOfHosp = from ClinHosp in db.ClinicHospitals
                                 where ClinHosp.ID == hospid
                                 select new SelectListItem()
                                 {
                                     Value = ClinHosp.ID.ToString(),
                                     Text = ClinHosp.ClinicHospitalName
                                 };
                returnmodel.itemSelection.AddRange(listOfHosp.ToList<SelectListItem>());
            }
            else
            {
                var listOfHosp = from ClinHosp in db.ClinicHospitals
                                 select new SelectListItem()
                                 {
                                     Value = ClinHosp.ID.ToString(),
                                     Text = ClinHosp.ClinicHospitalName
                                 };
                returnmodel.itemSelection.AddRange(listOfHosp.ToList<SelectListItem>());
            }

            //Doctor/Dentist MUST belong to a Hospital/Clinic
            //returnmodel.itemSelection.Add(new SelectListItem()
            //{

DAMS_03/Views/DoctorDentists/Create.cshtml
@model DAMS_03.Models.DoctorDentistCreateModel
@using DAMS_03.HtmlHelpers

@{
    ViewBag.Title = "Create";
}

<h2>Create Dentist</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorDentistID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorDentistID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxBookings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxBookings, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxBookings, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospClinID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @*@Html.DropDownListFor(model => model.HospClinID, Model.itemSelection, new { htmlAttributes = new { @class = "form-control input-group-sm" } })*@
                
                @BootstrapHtml.Dropdown("HospClinID", Model.itemSelection)

                @Html.ValidationMessageFor(model => model.HospClinID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "DoctorDentists")'">
                    Back to List
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DAMS_03/Views/DoctorDentists/Delete.cshtml
@model DAMS_03.Models.DoctorDentist

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Dentist</h2>

<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.DoctorDentistID, "Dentist ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DoctorDentistID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <button class="btn btn-primary" type="button"
                            onclick="location.href='@Url.Action("Index", "DoctorDentists")'">
                        Cancel
                    </button>
                </div>
            </div>
            @if (Request["error"] != null)
            {
                string errorNo = Request["error"];
                switch (errorNo)
                {
                    case ("547"):
                        <p style="color:red">Error : This entity cannot be deleted because it is being used by another entity.</p>
                        break;
                    default:

                        break;
                }//END switch
            }
        </div>
    }
</div>

DAMS_03/Views/DoctorDentists/Details.cshtml
@model DAMS_03.Models.DoctorDentistDetailModel

@{
    ViewBag.Title = "Details";
}

<h2>View Dentist Details</h2>

<div>
    <hr />
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.DoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorDentistID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MaxBookings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxBookings, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HospClin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospClin, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-success" type="button"
                        onclick="location.href='@Url.Action("Edit", "DoctorDentists", new { id = Model.ID})'">
                    Update
                </button>
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "DoctorDentists")'">
                    Back to List
                </button>
                <button class="btn btn-default" type="button"
                        onclick="location.href='@Url.Action("ViewSchedule", "DoctorDentists", new { id = Model.ID})'">
                    View Dentist's Schedule
                </button>
            </div>
        </div>
    </div>
</div>

DAMS_03/Views/DoctorDentists/Edit.cshtml
@model DAMS_03.Models.DoctorDentistEditModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Dentist</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorDentistID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorDentistID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorDentistID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MaxBookings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxBookings, new { htmlAttributes = new { @class = "form-control"} })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HospClin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospClin, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <button class="btn btn-primary" type="button"
                        onclick="location.href='@Url.Action("Index", "DoctorDentists")'">
                    Cancel
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DAMS_03/Views/DoctorDentists/Index.cshtml
@model List<DAMS_03.Models.DoctorDentistDetailModel>

@{
    ViewBag.Title = "Index";
}

<h2>View Dentists</h2>
<br/>

<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <div class="panel-title">
                List of Dentists
                @if (this.User.IsInRole("SysAdmin") || this.User.IsInRole("HospAdmin"))
                {
                    <button class="btn btn-default" type="button" style="float: right"
                            onclick="location.href='@Url.Action("Create", "DoctorDentists")'">
                        Create new
                    </button>
                }
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-hover table-sieve">
                        <thead>
                            <tr>
                                <th>
                                    Dentist ID
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model[0].Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model[0].HospClin)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model[0].MaxBookings)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="doctordentistAccountTableBody">
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].DoctorDentistID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].HospClin)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => modelItem[i].MaxBookings)
                                    </td>
                                    <td>
                                        <button class="btn btn-primary" type="button"
                                                onclick="location.href='@Url.Action("Details", "DoctorDentists", new { id = Model[i].ID })'">
                                            Details
                                        </button>
                                        @if (this.User.IsInRole("SysAdmin") || this.User.IsInRole("HospAdmin"))
                                        {
                                            <button class="btn btn-success" type="button"
                                                    onclick="location.href='@Url.Action("Edit", "DoctorDentists", new { id = Model[i].ID })'">
                                                Update
                                            </button>
                                            <button class="btn btn-danger" type="button"
                                                    onclick="location.href='@Url.Action("Delete", "DoctorDentists", new { id = Model[i].ID })'">
                                                Delete
                                            </button>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>